name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install SSH pass
      run: sudo apt-get install -y sshpass    

    - name: Copy files to VPS
      run: sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --exclude '.git' ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERNAME }}/cloudProject/

    - name: SSH and deploy
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /home/${{ secrets.SSH_USERNAME }}/cloudProject
        docker stop piksapp || true
        docker rm piksapp || true
        docker build -t piksapp .
        docker run -d -p 8000:8000 --name piksapp piksapp
        EOF