name: Deploy Django app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

    - name: SSH and deploy
      run: |
        ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
        cd /home/${{ secrets.SSH_USERNAME }}/cloudProject/
        git pull
        cd /home/${{ secrets.SSH_USERNAME }}/
        docker stop piksapp || true
        docker rm piksapp || true
        docker build -t piksapp .
        docker run -d -p 8000:8000 --name piksapp piksapp
